### ISSUE TITLE
Support objects in json structure.

### ISSUE THREAD

**Issue by lassiter** [candidco/confidential#12]
Currently, if you have a key inside an object in `<env>.json` that is 
```json
{
    'service': {   
              'api_key': 'secret:env/app/my_api_key',
              'base_url': 'url'
    }
}
```

It will not see the secret inside the service object.

However, if it's top level, it'll properly decrypt:

```json
{
   'another_key':  'secret:env/app/my_api_key'
}
```

### Steps to Reproduce

Take a working key from a top level of the json and place it inside the object like the first example. You should only see the the string stored in <env>.json from where you store your secret paths.

**Comment by vagelim** [comment]
Closed by #13
